[server]
headless = true
address = "0.0.0.0"
port = 8501
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0B3A82"
textColor = "#0b1220"   # dark text, avoids white-on-white
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
